version: 2
  jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    
    steps:
      - checkout
      - run:
          name: Hello greeting
          command: echo Hello, DevOps!
      - run:
          name: Print the time
          command: date
